# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214b52f9c595355ce081061ea8f211c50b0d9c638fa9af533c864d0464ffcdd08986d52f432104d3ca1c5947245b810ea10e37ecbba3cfabfc9aba54842dd125

test:
  secret_key_base: ffadc4d13bbb50f42f96f6b7a607094cb80bb9160bb84fa631130f0a0624069c44aca8a8177b28085e5fbce6bb96e272c954ab67f17b44311386ae659f82da66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
